name = "baenke-innichen-api"
main = "src/index.js"
compatibility_date = "2026-04-17"

[vars]
GITHUB_BACKUP_OWNER = "Stefan5687AA"
GITHUB_BACKUP_REPO = "Baenke-Innichen"
GITHUB_BACKUP_BRANCH = "main"
GITHUB_BACKUP_DIRECTORY = "backups"

[triggers]
crons = ["0 2 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "innichen-benches"
database_id = "5261e5f6-5c68-4668-a47c-14019a265813"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "baenke-innichen-images"
